default:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - api_failure
      - stale_schedule

image: ghcr.io/ansible/community-ansible-dev-tools:v25.5.2

variables:
  ANSIBLE_CONFIG: "${CI_PROJECT_DIR}/ansible.cfg"

stages:
  - lint
  - test ce
  - test pro


before_script:
  - ansible-galaxy collection install -r requirements.yml

include:
  - local: "/.gitlab-ci/jobs/lint.yml"
  - local: "/.gitlab-ci/jobs/test.yml"

