---
- name: Verify Passbolt installation
  hosts: all
  gather_facts: true
  vars_files:
    - ../../group_vars/all.yml
  tasks:
    - name: Verify MariaDB configuration
      ansible.builtin.import_tasks: verify/01_mariadb.yml
    - name: Verify Chrony (NTP) configuration
      ansible.builtin.import_tasks: verify/03_chrony.yml
    - name: Verify PHP configuration
      ansible.builtin.import_tasks: verify/04_php_configuration.yml
